version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:7.10'
    working_directory: ~/repo
    steps:
      - checkout
  deploy:
    docker:
      - image: 'circleci/node:7.10'
    working_directory: ~/repo
    steps:
      - run: 
          name: Echo NPM Token
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish to NPM
          command: sudo npm publish
workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
